# Generated by Django 2.0.2 on 2018-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0002_golfer_managed_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='golfer_city',
            field=models.TextField(blank=True, default='unknown'),
        ),
    ]
