# Generated by Django 2.0.2 on 2018-05-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0004_add_golfer_city_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golferroundscores',
            options={'managed': True, 'verbose_name': 'Golfer Round Scores', 'verbose_name_plural': 'Golfers Round Scores'},
        ),
    ]
